// <auto-generated />
using System;
using LinkShortening.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415115333_removeTestProperty")]
    partial class removeTestProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data.Models.UrlDl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("TransitionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LongUrl = "https://learn.microsoft.com/ru-ru/ef/ef6/modeling/code-first/migrations/automatic",
                            ShortUrl = "fafasf",
                            TransitionCount = 3
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LongUrl = "https://learn.microsoft.com/ru-ru/ef/ef6/modeling/code-first/migrations/",
                            ShortUrl = "dasds",
                            TransitionCount = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
